service: charge-simulation
runtime: nodejs16

handlers:
  - url: /
    secure: always
    static_files: dist/charge-simulation/index.html
    upload: dist/charge-simulation/index.html

  #  Routing rules for resources, css, js, images etc. Any file with format filename.ext
  - url: /(.*\.(.+))$
    secure: always
    static_files: dist/charge-simulation/\1
    upload: dist/charge-simulation/(.*\.(.+))$

  #  Routing rule for Angular Routing
  - url: /(.*)
    secure: always
    static_files: dist/charge-simulation/index.html
    upload: dist/charge-simulation/index.html